"""Preferred programmable session-construction workbench.

This module curates the byte-oriented synthesis tools that have driven the more
recent EOS / Magic-ID stability work. It is intentionally lower-level than the
legacy `ptxformatwriter.writer` API and is the better fit for building or splicing Pro
Tools sessions programmatically from known-good controls.
"""

from __future__ import annotations

from .body_synth import (
    add_audio_clip,
    add_click,
    add_click_anyN,
    add_clip_to_track,
    add_clips_to_tracks,
    add_midi_note,
    apply_insertions,
    block_bytes,
    build_audio_clips,
    changed_top_level_types,
    channel_count,
    clip_positions,
    extract_track,
    first_block_counter_value,
    flat_blocks,
    grow_one_track,
    move_click_to_top,
    overview_extent,
    overview_order,
    parse,
    rename_track,
    reorder_tracks,
    selected_tracks,
    session_name,
    set_clip_position,
    set_clip_wav,
    set_clip_wavs,
    set_markers,
    set_meter,
    set_meter_map,
    set_session_name,
    set_tempo,
    set_tempo_map,
    set_track_channels,
    set_track_names,
    synth_stereo_unit,
    synthesize_mixed_session,
    synthesize_mono_session,
    synthesize_stereo_inline,
    synthesize_stereo_session,
    track_channel_indices,
    track_name_occurrences,
    track_playlist_order,
    track_types,
    wav_clip_identity,
    wrap_raw_wav,
)
from .writer import encrypt_session_data, load_unxored, parse_unxored


__all__ = [
    "add_audio_clip",
    "add_click",
    "add_click_anyN",
    "add_clip_to_track",
    "add_clips_to_tracks",
    "add_midi_note",
    "apply_insertions",
    "block_bytes",
    "build_audio_clips",
    "changed_top_level_types",
    "channel_count",
    "clip_positions",
    "encrypt_session_data",
    "extract_track",
    "first_block_counter_value",
    "flat_blocks",
    "grow_one_track",
    "load_unxored",
    "move_click_to_top",
    "overview_extent",
    "overview_order",
    "parse",
    "parse_unxored",
    "rename_track",
    "reorder_tracks",
    "selected_tracks",
    "session_name",
    "set_clip_position",
    "set_clip_wav",
    "set_clip_wavs",
    "set_markers",
    "set_meter",
    "set_meter_map",
    "set_session_name",
    "set_tempo",
    "set_tempo_map",
    "set_track_channels",
    "set_track_names",
    "synth_stereo_unit",
    "synthesize_mixed_session",
    "synthesize_mono_session",
    "synthesize_stereo_inline",
    "synthesize_stereo_session",
    "track_channel_indices",
    "track_name_occurrences",
    "track_playlist_order",
    "track_types",
    "wav_clip_identity",
    "wrap_raw_wav",
]
